In [6]:
import numpy as np
import matplotlib.pyplot as plt
import IsingSystemClass as ISC

Hamiltonian
$$\begin{equation}\begin{aligned}H=-\frac{1}{2}\sum_{i,j}J_{ij}\sigma_i\sigma_j&&\sigma_i=\pm1&&\text{at each site }i\end{aligned}\end{equation}$$

Magnetization
$$\begin{equation}M=\sum_i\sigma_i\end{equation}$$

Coupling constant
$$\begin{equation}\left.J_{ij}=\left\{ \begin{array}{l}-1,~if ~\left|i-j\right| =1~or ~n-1\\
~~~0, ~others\end{array}\right.\right.\end{equation}$$

In [7]:
# Example usage:
n = 10
system = ISC.IsingSystem(n)

configurations = [7, 77, 777]

for config in configurations:
    system.set_spin_configuration(config)
    system.change_J(-1)

    M = system.calculate_total_magnetization()
    E = system.calculate_total_energy()

    print(f"For configuration {config}:")
    print(system.get_spin_state())
    print(f"Total Magnetization: {M}")
    print(f"Total Energy: {E}")
    print()

For configuration 7:
[-1 -1 -1 -1 -1 -1 -1  1  1  1]
Total Magnetization: -4
Total Energy: 6.0

For configuration 77:
[-1 -1 -1  1 -1 -1  1  1 -1  1]
Total Magnetization: -2
Total Energy: -2.0

For configuration 777:
[ 1  1 -1 -1 -1 -1  1 -1 -1  1]
Total Magnetization: -2
Total Energy: 2.0

